<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RSI1507" ignored="0" name="Suite de testes para projeto de automação em TDD" tests="6" failures="1" timestamp="2020-02-12T11:19:57 BRT" time="140.06" errors="0">
  <testcase name="testeDeCadastroFalha" time="12.601" classname="br.com.rsinet.hub_tdd.testes.Cadastro"/>
  <testcase name="testeDeCadastroSucesso" time="34.395" classname="br.com.rsinet.hub_tdd.testes.Cadastro">
    <failure type="java.lang.AssertionError" message="Cadastro efetuado com sucesso! did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Cadastro efetuado com sucesso! did not expect to find [true] but found [false]
at br.com.rsinet.hub_tdd.testes.Cadastro.testeDeCadastroSucesso(Cadastro.java:102)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testeDeCadastroSucesso -->
  <testcase name="testeDeBuscaPorLupaFalha" time="4.261" classname="br.com.rsinet.hub_tdd.testes.BuscaLupa"/>
  <testcase name="testeDeBuscaPorLupaSucesso" time="5.702" classname="br.com.rsinet.hub_tdd.testes.BuscaLupa"/>
  <testcase name="testeDeBuscaPorTelaInicialFalha" time="17.075" classname="br.com.rsinet.hub_tdd.testes.BuscaHome"/>
  <testcase name="testeDeBuscaPorTelaInicialSucesso" time="11.512" classname="br.com.rsinet.hub_tdd.testes.BuscaHome"/>
</testsuite> <!-- Suite de testes para projeto de automação em TDD -->
